### ISSUE TITLE
Question about rapids

### ISSUE THREAD

**Issue by georgekasa** [shwina/rapids-tutorial-gtc-2023#1]
Hello,
I just saw you in Nvidia gtc 2023, recently I got my first certificate from nvidia  Accelerating End-to-End Data Science Workflows.
I am always using now cudf, cuml and cupy. I want to ask you if there will be coming more from you about rapids and big data sets how to handle them.
Amazing job!!!!!!
( your twitter link is broken, so I could not send u a message.

**Comment by shwina** [comment]
Thanks for the feedback @georgekasa! I'm glad you found the talk helpful. For large workloads that do not fit in memory, one option is to use Dask with cuDF: https://medium.com/rapids-ai/easy-cpu-gpu-arrays-and-dataframes-run-your-dask-code-where-youd-like-e349d92351d
